services:
  magic:
    image: mageai/mageai:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MAGE_DATABASE_URL:
      ports:
      - 6789:6789
    volumes:
      - ./modules:/home/src/
    restart: on-failure:5
  postgres:
    image: postgres:latest
    restart: on-failure
    container_name: explore-postgres

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: p@ssword
    ports:
      - "5432:5432"
