services:
  magic:
    image: mageai/mageai:latest
    command: mage start explore
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MAGE_DATABASE_CONNECTION_URL: postgresql+psycopg2://root:p@ssword@postgres:5432/postgres
    ports:
        - "6789:6789"
    volumes:
      - ./:/home/src/
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: explore-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: p@ssword
    ports:
      - "5432:5432"
